CREATE DATABASE IF NOT EXISTS bd_productos;
CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_categorias;
CREATE DATABASE IF NOT EXISTS bd_marcas;
CREATE DATABASE IF NOT EXISTS bd_pedidos;
CREATE DATABASE IF NOT EXISTS bd_inventario;
CREATE DATABASE IF NOT EXISTS bd_carrito;
CREATE DATABASE IF NOT EXISTS bd_pagos;
